### ISSUE TITLE
Wallets Section?

### ISSUE THREAD

**Issue by l3wi** [ertugrulyilmaz/awesome-iota#1]
Desktop Wallet: https://github.com/iotaledger/wallet
Web Wallet: https://github.com/danilind/iota-web-wallet/
Android: https://github.com/iotaledger/android-wallet-app
iOS: https://github.com/l3wi/iotaMobile

**Comment by ertugrulyilmaz** [comment]
Thanks @l3wi i will added this section.

[commit](https://github.com/ertugrulyilmaz/awesome-iota/commit/8fcf5eea8f37bf2912383809c00197dc6f8f5d44)
