### ISSUE TITLE
README.md could do with 1-sentence answer to "What is IOTA?" inline.

### ISSUE THREAD

**Issue by DamonHD** [ertugrulyilmaz/awesome-iota#2]
I didn't know, still don't exactly, and wasn't about to download a potentially huge PDF to find out.

**Comment by ertugrulyilmaz** [comment]
@DamonHD sorry i didn't understand what you mean?

**Comment by DamonHD** [comment]
There is no short explanation of what IOTA is on the front page itself.  If someone news comes fresh from (say) HackerNews you lose the chance to engage them.  I work in IoT and didn't recognise the acronym.

**Comment by ertugrulyilmaz** [comment]
@DamonHD ok i got it.

what about this?

> **IOTA** is a revolutionary new transactional settlement and data integrity layer for the Internet of Things. It’s based on a new distributed ledger architecture, the **Tangle**, which overcomes the inefficiencies of current **Blockchain** designs and introduces a new way of reaching consensus in a **decentralized peer-to-peer system**. For the first time ever, through IOTA people can transfer money without any fees. This means that even infinitesimally small nanopayments can be made through IOTA.
> 
> **IOTA** is the missing puzzle piece for **the Machine Economy** to fully emerge and reach its desired potential. We envision IOTA to be the public, permissionless backbone for the Internet of Things that enables true interoperability between all devices.
