### ISSUE TITLE
Here are some other links to add, and a suggestion (and mistake found)

### ISSUE THREAD

**Issue by ghost** [ertugrulyilmaz/awesome-iota#3]
Here are some more links to add.

https://aboutiota.info/ - All About IOTA
http://iotabalance.com/ - Minimalist IOTA Balance Lookup
http://tangler.org/ - Tangle Explorer
http://iotachina.com/ - IOTA China 首页
http://iotaitalia.com/ - IOTA Italia
http://blog.naver.com/iotakorea - IOTA 한국
http://lhj.hatenablog.jp/entry/iota - IOTA 日本
https://blog.iota.org/iota-ecosystem-fund-2-million-f6ade6a4d8ba - Ecosystem Fund Post

A mistake: Under Blogs & Sites
The title Wikipedia is linking to trustediot.org and the description is the link to wikipedia.
I think Wikipedia should be at the top in the About section.

**Comment by ertugrulyilmaz** [comment]
@stockermans thanks for links. i added all of them. and moved wikipedia links to about section.
